package io.github.siyukio.client.interceptor;

import com.github.benmanes.caffeine.cache.Cache;
import io.github.siyukio.tools.util.XDataUtils;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.client.ClientHttpRequestExecution;
import org.springframework.http.client.ClientHttpRequestInterceptor;
import org.springframework.http.client.ClientHttpResponse;

import java.io.IOException;
import java.net.URI;
import java.nio.charset.StandardCharsets;

/**
 * A {@link ClientHttpRequestInterceptor} that caches HTTP response bodies using a Caffeine cache.
 * <p>
 * The cache key is generated by combining the request URI and the request body (JSON string).
 * On a cache hit, the cached JSON response is returned directly via {@link LocalJsonResponse}
 * without executing the actual HTTP request.
 * </p>
 *
 * @author Bugee
 */
@Slf4j
public class CacheRequestInterceptor implements ClientHttpRequestInterceptor {

    private final Cache<String, String> cache;

    public CacheRequestInterceptor(Cache<String, String> cache) {
        this.cache = cache;
    }

    @Override
    public ClientHttpResponse intercept(org.springframework.http.HttpRequest request, byte[] body,
                                        ClientHttpRequestExecution execution) throws IOException {
        URI uri = request.getURI();
        String cacheKey = generateCacheKey(uri, body);

        // Return cached response if present
        String cachedValue = cache.getIfPresent(cacheKey);
        if (cachedValue != null) {
            log.debug("Cache hit for key: {}", cacheKey);
            return new LocalJsonResponse(XDataUtils.toJSONString(cachedValue));
        }

        log.debug("Cache miss for key: {}, executing request", cacheKey);
        ClientHttpResponse response = execution.execute(request, body);

        if (response.getStatusCode() != HttpStatus.OK) {
            return response;
        }

        MediaType contentType = response.getHeaders().getContentType();
        if (contentType == null || !contentType.equals(MediaType.APPLICATION_JSON)) {
            return response;
        }

        // Read response body and cache it
        byte[] responseBody = response.getBody().readAllBytes();
        String responseBodyStr = new String(responseBody, StandardCharsets.UTF_8);
        cache.put(cacheKey, responseBodyStr);

        return new StringResponseWrapper(response, responseBodyStr);
    }

    /**
     * Generate a cache key by combining the request URI and body content.
     *
     * @param uri  the request URI
     * @param body the request body as raw bytes
     * @return a unique cache key string
     */
    private String generateCacheKey(URI uri, byte[] body) {
        String bodyStr = body != null && body.length > 0
                ? new String(body, StandardCharsets.UTF_8)
                : "";
        return uri.toString() + "|" + bodyStr;
    }

}
