package io.github.siyukio.client.interceptor;

import com.github.benmanes.caffeine.cache.Cache;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.client.ClientHttpRequestExecution;
import org.springframework.http.client.ClientHttpRequestInterceptor;
import org.springframework.http.client.ClientHttpResponse;
import org.springframework.util.StringUtils;

import java.io.IOException;
import java.net.URI;
import java.nio.charset.StandardCharsets;

/**
 * A {@link ClientHttpRequestInterceptor} that caches HTTP response bodies using a Caffeine cache.
 * <p>
 * The cache key is generated by combining the request URI and the request body (JSON string).
 * On a cache hit, the cached JSON response is returned directly via {@link LocalJsonResponse}
 * without executing the actual HTTP request.
 * </p>
 *
 * @author Bugee
 */
@Slf4j
public class CacheAfterRequestInterceptor implements ClientHttpRequestInterceptor {

    private final Cache<String, String> cache;

    public CacheAfterRequestInterceptor(Cache<String, String> cache) {
        this.cache = cache;
    }

    @Override
    public ClientHttpResponse intercept(org.springframework.http.HttpRequest request, byte[] body,
                                        ClientHttpRequestExecution execution) throws IOException {
        ClientHttpResponse response = execution.execute(request, body);

        if (response.getStatusCode() != HttpStatus.OK) {
            return response;
        }

        MediaType contentType = response.getHeaders().getContentType();
        if (contentType == null || !contentType.equals(MediaType.APPLICATION_JSON)) {
            return response;
        }

        String cacheControl = response.getHeaders().getCacheControl();
        if (StringUtils.hasText(cacheControl) && cacheControl.equals("no-store")) {
            return response;
        }

        // Read response body and cache it
        byte[] responseBody = response.getBody().readAllBytes();
        String responseBodyStr = new String(responseBody, StandardCharsets.UTF_8);
        if (StringUtils.hasText(responseBodyStr)) {
            URI uri = request.getURI();
            String cacheKey = generateCacheKey(uri, body);
            cache.put(cacheKey, responseBodyStr);
            log.debug("Cache key: {}", cacheKey);
        }

        return response;
    }

    /**
     * Generate a cache key by combining the request URI and body content.
     *
     * @param uri  the request URI
     * @param body the request body as raw bytes
     * @return a unique cache key string
     */
    private String generateCacheKey(URI uri, byte[] body) {
        String bodyStr = body != null && body.length > 0
                ? new String(body, StandardCharsets.UTF_8)
                : "";
        return uri.toString() + "|" + bodyStr;
    }

}
