name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Debug current context
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
          echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
          echo "CI: $CI"

      - name: Deploy to Maven Central
        run: mvn --batch-mode --no-transfer-progress clean deploy -Prelease
        env:
          CI_MAVEN_USERNAME: ${{ secrets.CI_MAVEN_USERNAME }}
          CI_MAVEN_PASSWORD: ${{ secrets.CI_MAVEN_PASSWORD }}