name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install semantic-release @semantic-release/changelog @semantic-release/github -D

      - name: Debug token and remote
        run: |
          echo "Token length: ${#GITHUB_TOKEN}"
          echo "Preview token: ${GITHUB_TOKEN:0:20}*****"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/siyukio/spring-siyukio.git
          git remote -v
          curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
        run: npx semantic-release